// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    username,
    user_agent ,
    user_ip ,
    refresh_token,
    is_blocked,
    refresh_token_expired_at
) VALUES (
  $1, $2,$3,$4,$5,$6,$7
)
RETURNING id, username, user_agent, user_ip, refresh_token, is_blocked, refresh_token_expired_at, expired_at
`

type CreateSessionParams struct {
	ID                    uuid.UUID `json:"id"`
	Username              string    `json:"username"`
	UserAgent             string    `json:"user_agent"`
	UserIp                string    `json:"user_ip"`
	RefreshToken          string    `json:"refresh_token"`
	IsBlocked             bool      `json:"is_blocked"`
	RefreshTokenExpiredAt time.Time `json:"refresh_token_expired_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.Username,
		arg.UserAgent,
		arg.UserIp,
		arg.RefreshToken,
		arg.IsBlocked,
		arg.RefreshTokenExpiredAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserAgent,
		&i.UserIp,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.RefreshTokenExpiredAt,
		&i.ExpiredAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, username, user_agent, user_ip, refresh_token, is_blocked, refresh_token_expired_at, expired_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserAgent,
		&i.UserIp,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.RefreshTokenExpiredAt,
		&i.ExpiredAt,
	)
	return i, err
}
